### PR TITLE
Update SimAVR version

### PR DESCRIPTION
**Pull request by gergoerdi**
This pull requests updates the included SimAVR version to the latest one. It also updates the included `avr-libc` header files so it's not necessary anymore to exclude parts of SimAVR from the build.

### CODE REVIEW

**Comment by Premik** [comment]
Good stuff. Thanks. Updating the underlying simavr is indeed needed. Just few comments:
- Note the upstream repo is ponty/pysimavr. So it would be better to open PR there at some stage.
- There are probably more changes required because of the version upgrade. One thing I'm aware of is the log levels were shifted to different values. But this could be fixed later.
- Could you please re-run the swig wrappers generation using the 3.0.8 version? As that is what is currently used. The best way to do this is using Vagrant as it gives all the devs same reference environment. The way I do it:

Inside to project root (where the Vagrantfile is):
```
vagrant up
vagrant ssh
```
Then inside the vm:

```bash
cd /vagrant/pysimavr/swig
scons -c
rm *.so *.os *.pyc #Just extra cleanup as Scons only purges files it knows about
scons
```

And to further install the files and run the tests:

```bash
cd /vagrant
python3 ./setup.py build --force
#python ./setup.py build --force

sudo python3 ./setup.py install
#sudo python ./setup.py install

#Clean local files to ensure system files are used
cd /vagrant/pysimavr/swig
scons -c

#Smoke test
python3 -c "from pysimavr.avr import Avr"
#python -c "from pysimavr.avr import Avr"


cd /vagrant/tests

#Run all tests
python3 /usr/local/bin/nosetests  .
#nosetests -v --cover-package=pysimavr .
```

This would be for python3. Python2 commands are commented out.

**Comment by gergoerdi** [comment]
OK I've updated via Vagrand. I was not expecting it to use 3.3G of disk space...

**Comment by Premik** [comment]
I pulled the commits into a fresh [branch.](/Premik/pysimavr/tree/gergoerdi-update-simavr) I don't want to merge these into the *IRQCallback* one since there is already a PR opened ponty/pysimavr#33.  And that would push these commits under that very same PR.

**Comment by Premik** [comment]
3.3G seems quite odd. My vagrant has like 300MB. But I never ran the "'make' inside simavr".

**Comment by Premik** [comment]
I've merged this also into my master branch. As the two pending pr I have opened upstreem are stalled apparently. 

Should you do any further pr please open them against the master.

**Pull request closed without merging**
